SFC + Компоненты - исправления
js-tasks-ru/vue-20230120_moiseevaviktoriya pull request #4
Opened 2023-02-02 14:12 UTC by viktoriyaMoiseeva

2023-02-02 14:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-06 17:34 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-07 22:02 UTC, ShGKme requested changes
В `04-vue-cli/02-TheToaster` требуется:
- Убрать лишний параметр `id` компонента, который не управляет его работой
- Не передавать на компонент класс, который описан в стилях внутри этого компонента

В `04-vue-cli/04-MeetupsCalendar` также есть комментарии по работе с данными, но их можно будет исправить в следующей итерации разработки этого компонента в другой теме.

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    },
С событием незачем отдавать `id`, который этому компоненту в целом не нужен. Его родитель итак знает, у какого тоста порождается событие `deleteToast`. Он знает этот `id`, который сейчас получается вместе с событием, потому что он сам же ему его отдаёт. Сейчас `id` просто получается от родителя и отправляется ему же обратно.

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +      }
Этот параметр на самом деле не нужен для работы компонента. Тост может функционировать без ID

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    </ui-toast>
Здесь `TheToaster` передаёт в `UiToast` `:id="toast.id"`, а потом его же ловит и использует в ` @deleteToast="deleteToast"`. Вместо отправки ID по кругу можно явно передать его сразу: ` @deleteToast="deleteToast(toast.id)"`.

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    </ui-toast>
Этот компонент сам отвечает за вывод одного тоста и знает о тостах разных типов. Именно в нём сейчас у вас описаны классы `toast_success` и `toast_error`. В этом случае лучше ему же определять, какие классы должны быть у разных типов тостов.

Сейчас об этом должен знать пользователь компонента, который должен передать правильное имя класса из этого компонента, подсмотрев его в исходнике компонента.

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Лучше не использовать время (`Date.now`) в качестве идентификатора. Не гарантируется его уникальность. Вместо времени может быть инкрементный идентификатор (просто делать `lastId++` на уровне модуля компонента), или случайный (`nanoid`, `uuid`).

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      </select>
`style="visibility: hidden"` делает элемент невидимым, но оставляет его в потоке рендеринга. Здесь это незаметно из-за абсолютного позиционирования, но это некорректно для скрытия элемента. Скрывать его полностью можно через `display: none` или во Vue через `v-show="false"`.

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendarCell.vue
> +      },
Если значение по умолчанию не примитивное (число, строка), то оно должно описываться функцией, возвращающей значение. Сейчас у всех `MeetupsCalendarCell` дата по умолчанию - это ссылка на один общий один раз созданный `new Date()`.

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    }
Во многих местах решение получилось сложнее из-за использования даты не по UTC, как в timestamp дате митапа, а работе в локальном часовом поясе. Для работы в UTC нужны UTC методы работы с датой, например, `getUTCDate`.

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
Вычисляемое свойства - это именно свойства. Для них описывается функция, с помощью которой Vue будет вычислять значение вычисляемого свойства, но оно остаётся свойством. По этой причине вычисляемые свойства обычно называют, как свойства, а не как функции (не с глагола, без get).

2023-02-07 22:02 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +        :class="{'calendar-view__cell_inactive' : !isActive(date)}"/>
Сейчас в методе во время рендеринга вызывается метод. Вызывать метод в шаблоне в целом обычно не лучшая практика. Это делает шаблон не декларативным, и требует дополнительно проверять, что метод не имеет побочных эффектов и производительный. Иногда это допустимо, когда метод используется для форматирования вывода или немного упрощает код в компоненте. Например, как метод `isActive`.

Но метод `getMeetupsByDate` здесь используется для описания логики работы с данными - формирует массив данных для дочернего компонента прямо во время рендеринга. Это уже перетекание логики обработки данных в шаблон, при этом неоптимальное.

Сейчас при рендеринге КАЖДОЙ ячейки календаря происходит перебор всех-всех митапов (включая те, которые вообще не относятся к этому месяцу или уже выводились в другой ячейки) для проверки, а не попадает ли этот митап в эту ячейку. Потом ещё раз для следующей ячейки. И так для всех дней месяца. И всё это повторяется при каждом ререндеринге компонента, даже если результат не изменится.

Вместо этого лучше готовить данные для их удобного вывода без дополнительных перевычислений.

2023-02-11 20:16 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-12 16:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-12 16:58 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-02-12 17:00 UTC, merged