Реактивность
js-tasks-ru/vue-20230120_moiseevaviktoriya pull request #6
Opened 2023-02-23 13:25 UTC by viktoriyaMoiseeva

2023-02-23 13:26 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-23 19:43 UTC, ShGKme requested changes
В `08-reactivity/05-reactify` маленькая проблема, остальные задачи приняты.

2023-02-23 19:43 UTC, ShGKme commented on 08-reactivity/05-reactify/utils/reactify.js
> +    });
Если аргумент - это объект, нельзя быть уверенным, что это именно `ref`. Могут быть обычные JS объекты. Для проверки на реф можно использовать функцию `isRef`. А в качестве такого тернарника ещё более удобную функцию - `unref(arg)`, которая как раз позволяет разворачивать реф в таких ситуациях.

2023-02-27 13:22 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-27 16:52 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-02-27 16:53 UTC, merged