11. Slots
js-tasks-ru/vue-20230120_moiseevaviktoriya pull request #7
Opened 2023-03-01 19:18 UTC by viktoriyaMoiseeva

2023-03-01 19:19 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-03-01 21:45 UTC, ShGKme requested changes
Компоненты работают. Но лучше подумать, как сделать вывод более оптимальным, без обработки данных прямо во время рендера

2023-03-01 21:45 UTC, ShGKme commented on 10-slots/01-UiPaginationView/components/UiPaginationView.vue
> +    </template>
v-for можно использовать сразу на <slot>

2023-03-01 21:45 UTC, ShGKme commented on 10-slots/03-UiCalendarView/components/MeetupsCalendar.vue
>  };
Сейчас во время рендеринга вызывается метод. Вызывать метод в шаблоне в целом обычно не лучшая практика. Это делает шаблон не декларативным, и требует дополнительно проверять, что метод не имеет побочных эффектов и производительный. Иногда это допустимо, когда метод используется для форматирования вывода или немного упрощает код в компоненте. Например, как метод `isActive`.

Но метод `getMeetupsByDate` здесь используется для описания логики работы с данными - формирует массив данных для дочернего компонента прямо во время рендеринга. Это уже перетекание логики обработки данных в шаблон, при этом неоптимальное.

Сейчас при рендеринге КАЖДОЙ ячейки календаря происходит перебор всех-всех митапов (включая те, которые вообще не относятся к этому месяцу или уже выводились в другой ячейки) для проверки, а не попадает ли этот митап в эту ячейку. Потом ещё раз для следующей ячейки. И так для всех дней месяца. И всё это повторяется при каждом ререндеринге компонента, даже если результат не изменится.

Вместо этого лучше готовить данные для их удобного вывода без дополнительных перевычислений.

2023-03-01 21:45 UTC, ShGKme commented on 10-slots/03-UiCalendarView/components/InternationalHolidaysCalendar.vue
> +    }
Аналогично. Кроме того, в этом компоненте уже есть вариант подготовки данных

2023-03-02 16:34 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-03-02 21:15 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-03-02 21:16 UTC, merged